[2025-07-18T07:44:27.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T07:44:27.296+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl.run_etl manual__2025-07-18T07:43:46.385325+00:00 [queued]>
[2025-07-18T07:44:27.305+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl.run_etl manual__2025-07-18T07:43:46.385325+00:00 [queued]>
[2025-07-18T07:44:27.306+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-18T07:44:27.334+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_etl> on 2025-07-18 07:43:46.385325+00:00
[2025-07-18T07:44:27.343+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecommerce_etl', 'run_etl', 'manual__2025-07-18T07:43:46.385325+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmpm99lfycy']
[2025-07-18T07:44:27.347+0000] {logging_mixin.py:188} WARNING - /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8706) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-18T07:44:27.347+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask run_etl
[2025-07-18T07:44:27.348+0000] {standard_task_runner.py:63} INFO - Started process 8740 to run task
[2025-07-18T07:44:27.422+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_etl.run_etl manual__2025-07-18T07:43:46.385325+00:00 [running]> on host LAPTOP-2CRA05LG.
[2025-07-18T07:44:27.641+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecommerce_etl' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T07:43:46.385325+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T07:43:46.385325+00:00'
[2025-07-18T07:44:27.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T07:44:27.646+0000] {logging_mixin.py:188} INFO - Creating SparkSession with appName: EcommerceSalesAnalytics and master: local[*]
[2025-07-18T07:44:28.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T07:44:28.270+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/airflow/dags/ecommerce_etl_dag.py", line 24, in run_etl
    spark = create_spark_session()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/src/utils/spark_session.py", line 14, in create_spark_session
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-07-18T07:44:28.326+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_etl, task_id=run_etl, run_id=manual__2025-07-18T07:43:46.385325+00:00, execution_date=20250718T074346, start_date=20250718T074427, end_date=20250718T074428
[2025-07-18T07:44:28.367+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task run_etl ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 8740)
[2025-07-18T07:44:28.408+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-18T07:44:28.433+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T07:44:28.437+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
