[2025-07-18T09:29:43.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T09:29:43.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl.run_etl manual__2025-07-18T09:29:07.556051+00:00 [queued]>
[2025-07-18T09:29:44.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl.run_etl manual__2025-07-18T09:29:07.556051+00:00 [queued]>
[2025-07-18T09:29:44.018+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-18T09:29:44.064+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_etl> on 2025-07-18 09:29:07.556051+00:00
[2025-07-18T09:29:44.072+0000] {standard_task_runner.py:63} INFO - Started process 21660 to run task
[2025-07-18T09:29:44.076+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecommerce_etl', 'run_etl', 'manual__2025-07-18T09:29:07.556051+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmp65k3e2qn']
[2025-07-18T09:29:44.080+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask run_etl
[2025-07-18T09:29:44.723+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_etl.run_etl manual__2025-07-18T09:29:07.556051+00:00 [running]> on host LAPTOP-2CRA05LG.
[2025-07-18T09:29:45.036+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecommerce_etl' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T09:29:07.556051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T09:29:07.556051+00:00'
[2025-07-18T09:29:45.040+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T09:29:45.242+0000] {logging_mixin.py:188} INFO - Creating SparkSession with appName: EcommerceSalesAnalytics and master: local[*]
[2025-07-18T09:30:06.758+0000] {logging_mixin.py:188} INFO - SparkSession created successfully.
[2025-07-18T09:30:06.761+0000] {logging_mixin.py:188} INFO - Attempting to read from: /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/data/raw/orders.csv
[2025-07-18T09:30:21.061+0000] {logging_mixin.py:188} INFO - Attempting to read from: /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/data/raw/customers.csv
[2025-07-18T09:30:21.756+0000] {logging_mixin.py:188} INFO - Attempting to read from: /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/data/raw/products.csv
[2025-07-18T09:30:22.727+0000] {logging_mixin.py:188} INFO - Attempting to write to: /mnt/c/Users/Shivam.../output/
[2025-07-18T09:30:22.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T09:30:22.742+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/airflow/dags/ecommerce_etl_dag.py", line 34, in run_etl
    write_output(enriched_df, output_path)
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/data_engineering/data_engineering_project/batch-etl-pyspark/src/etl/load.py", line 13, in write_output
    df.write.format(output_format).mode(mode).save(output_path)
    ^^^^^^^^
AttributeError: 'tuple' object has no attribute 'write'
[2025-07-18T09:30:22.806+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_etl, task_id=run_etl, run_id=manual__2025-07-18T09:29:07.556051+00:00, execution_date=20250718T092907, start_date=20250718T092944, end_date=20250718T093022
[2025-07-18T09:30:22.878+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task run_etl ('tuple' object has no attribute 'write'; 21660)
[2025-07-18T09:30:22.910+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-18T09:30:22.965+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T09:30:22.980+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
